<?php
$studenti=[
    [        
        "nome"=>"Samuele",
        "cognome"=>"Madrigali",
        "voti"=>[10,10,10,10,10],
    ],
    [        
        "nome"=>"Alessandra",
        "cognome"=>"Madrigali",
        "voti"=>[rand(2,10),rand(2,10),rand(2,10),rand(2,10),rand(2,10)],
    ],
    [        
        "nome"=>"Nemo",
        "cognome"=>"Madrigali",
        "voti"=>[rand(2,10),rand(2,10),rand(2,10),rand(2,10),rand(2,10)],
    ],
];